import 'dart:async';
import 'dart:io';

import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'connectivity_service.g.dart'; // Will be generated by build_runner

/// Service for checking network connectivity
@riverpod
ConnectivityService connectivityService(ConnectivityServiceRef ref) {
  return ConnectivityService();
}

class ConnectivityService {
  // Host used to probe connectivity. Using a stable public host keeps this simple.
  // If you prefer, we can switch this to your Supabase project domain.
  static const String _probeHost = 'example.com';

  // How often to poll for connectivity changes in the stream.
  static const Duration _pollInterval = Duration(seconds: 5);

  /// Check if device is currently online
  Future<bool> isOnline() async {
    try {
      final results = await InternetAddress.lookup(_probeHost)
          .timeout(const Duration(seconds: 3));
      return results.isNotEmpty && results.first.rawAddress.isNotEmpty;
    } on SocketException {
      return false;
    } on TimeoutException {
      return false;
    }
  }

  /// Stream of connectivity changes
  ///
  /// This implements a simple polling-based connectivity stream that emits
  /// `true` when online and `false` when offline. Values are de-duplicated.
  Stream<bool> get connectivityStream {
    return Stream<void>.periodic(_pollInterval)
        .asyncMap((_) => isOnline())
        .distinct();
  }

  /// Convenience: one-shot connectivity check via the stream pipeline.
  Future<bool> isOnlineFromStream() async {
    return isOnline();
  }
}

